### ISSUE TITLE
Unable to rub the code on GPU

### ISSUE THREAD

**Issue by hsmmoj** [deepmind/jax_verify#9]
**I am trying to run the code on GPU, but getting the following error:**

  File "/home/hesam/anaconda3/lib/python3.10/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: nvlink exited with non-zero error code 256, output: nvlink fatal   : Input file '/tmp/tempfile-hesam-System-Product-Name-9fa0db7-13565-6002898000b0d.cubin' newer than toolkit (122 vs 120)
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hesam/Desktop/UCSD/SOC/codes/jax_verify-master/examples/run_sdp_verify.py", line 244, in <module>
    app.run(main)
  File "/home/hesam/anaconda3/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/hesam/anaconda3/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/hesam/Desktop/UCSD/SOC/codes/jax_verify-master/examples/run_sdp_verify.py", line 180, in main
    run_verification(PickleWriter())
  File "/home/hesam/Desktop/UCSD/SOC/codes/jax_verify-master/examples/run_sdp_verify.py", line 202, in run_verification
    verif_instance = get_verif_instance(
  File "/home/hesam/Desktop/UCSD/SOC/codes/jax_verify-master/examples/run_sdp_verify.py", line 112, in get_verif_instance
    bounds = boundprop_utils.boundprop(
  File "/home/hesam/Desktop/UCSD/SOC/codes/jax_verify-master/examples/jax_verify/extensions/sdp_verify/boundprop_utils.py", line 56, in boundprop
    return boundprop_method(params, x, epsilon, input_bounds,
  File "/home/hesam/Desktop/UCSD/SOC/codes/jax_verify-master/examples/jax_verify/extensions/sdp_verify/boundprop_utils.py", line 67, in _crown_ibp_boundprop
    jnp.maximum(x - epsilon, input_bounds[0]),
**jaxlib.xla_extension.XlaRuntimeError: INTERNAL: nvlink exited with non-zero error code 256, output: nvlink fatal   : Input file '/tmp/tempfile-hesam-System-Product-Name-9fa0db7-13565-6002898000b0d.cubin' newer than toolkit (122 vs 120**)

**CUDA version: 12.0
CUDNN version: 8.9**

**Comment by bunelr** [comment]
This looks like a jax / cuda error. Are you sure than Jax and Cuda are correctly installed?
Are you able to run some normal operations?
